### ISSUE TITLE
New VPN IP address additions

### ISSUE THREAD

**Issue by Xenophilicy** [Cosmoverse/AntiVPN#2]
ExpressVPN:
- USA - New York: `45.41.134.170`
- USA - San Francisco: `104.143.92.210`
- USA - Chicago: `173.239.199.30`
- USA - Washington: `104.194.218.252`
- USA - Dallas: `193.56.117.26`
- USA - Los Angeles (Server 2): `104.238.46.205`
- USA - Miami (Server 2): `104.238.59.219`
- USA - Seattle: `46.244.28.56`

**Comment by Muqsit** [comment]
Indexed 👍
